# mutation_rarity_weights.py

"""
🎯 Mutation Rarity Weight Tables

Defines the probability distribution for technique evolution mutations.

Each mutation offer is generated by randomly selecting a rarity
from a weighted table. These weights are affected by the actor’s
current *boost level* for the relevant skill.

Boosts are obtained by spending banked mutations. They increase
the quality of future mutation offers by excluding lower tiers
from the rarity pool.

---

📊 Boost Level Effects:

| Boost Level | Eligible Rarities          |
|-------------|-----------------------------|
| 0           | common, uncommon, rare, epic |
| 1           | uncommon, rare, epic         |
| 2           | rare, epic                   |
| 3+          | epic only                    |

Each rarity has a base weight representing its likelihood.

Note: These are NOT player-visible rarity drop rates; they are
internal tuning parameters for the mutation system.

---
"""

RARITY_WEIGHTS_BY_BOOST = {
    0: {
        "common": 60,
        "uncommon": 25,
        "rare": 10,
        "epic": 5
    },
    1: {
        "uncommon": 60,
        "rare": 25,
        "epic": 15
    },
    2: {
        "rare": 70,
        "epic": 30
    },
    3: {
        "epic": 100
    }
}
