# config/config.py
# [AI]
# [PERMANENT]
# Generated by assistant under integrator review
# Must follow locked contracts and tagging rules

"""Global configuration toggles for runtime behavior.
Used to control debug logging, simulation flags, and runtime settings.

@tags: ["system", "event_data", "data_schema", "always"]
@status: "permanent"
"""

# Debug mode toggle used across all runtime systems.
# @tags: ["system", "event_data", "data_schema", "always"]
# @status: "permanent"
DEBUG_MODE = True
